package configuration

object EnvNames {
  val SCHEMA_REGISTRY_URL = "SCHEMA_REGISTRY_URL"

  val DATABASE_POLL_INTERVAL = "DATABASE_POLL_INTERVAL"

  val QUERY_PAGE_SIZE = "QUERY_PAGE_SIZE"

  val WEB_SOCKET_BUFFER_SIZE = "WEB_SOCKET_BUFFER_SIZE"

  val KAFKA_BOOTSTRAP_SERVERS = "KAFKA_BOOTSTRAP_SERVERS"

  val KAFKA_TOPICS = "KAFKA_TOPICS"
}
